### ISSUE TITLE
New nodes are created when old are renamed ?

### ISSUE THREAD

**Issue by sebastiandammark** [sotirisf/Umbraco-AutoNode#8]
If AutoNode creates a node called Local Content of the type LocalContent and I rename that one to Modules.

Next time I publish the parent page AutoNode creates a new node named Local Content of the type LocalContent

It would be nice if the package only looked at the DocumentType and not the name.

**Comment by sotirisf** [comment]
Yes, that's the default behavior. AutoNode checks children for a combination of doctype + node name in order to decide whether to create a node or not. However, your suggestion is a very good idea - I could add a setting that would allow for either only checking children doctypes or doctype + nodename per rule. I'll put it on the next update.

**Comment by sebastiandammark** [comment]
That would be very nice.
It's a problem when doing multilingual sites :)

**Comment by sotirisf** [comment]
I pushed a change with a new parameter for rules that you can also use in the autonode.config file. createIfExistsWithDifferentName - default is true (to keep compatibility with previous versions, meaning that it checks both doctype and name in order to decide whether to create the new node or not) but you can set it to false to prevent the name check and have it only check the doctype - essentially preventing creation of a new node when there already is one with the given doctype, regardless of name.  Be  advised that there's also another change fixing a bug that appeared on Umbraco 7.6 and up, references are now for 7.6 and target framework is net461 (was 452)
